Repository semaphore-protocol/website, pull requests merged in 2023-01, with the labels that each got.

#35 Groups.md broken links
  versioned_docs/version-V2/guides/groups.md
Labels: documentation

#43 Fix minor typos
  versioned_docs/version-V2/quick-setup.md
  versioned_docs/version-V2/use-cases/private-voting.md
Labels: documentation 📖

#47 fix: typo and broken link in proof guide
  versioned_docs/version-V2/guides/proofs.md
Labels: documentation 📖

#48 fix contracts link
  versioned_docs/version-V2/technical-reference/contracts.md
Labels: documentation 📖

#56 PSE Twitter link in the footer
  i18n/en/code.json
  i18n/es/code.json
  src/theme/Footer/index.tsx
Labels: documentation 📖

#62 more fixes to contracts links
  versioned_docs/version-V2/technical-reference/contracts.md
Labels: documentation 📖

#59 Spanish translation
  i18n/es/code.json
  i18n/es/docusaurus-plugin-content-docs/version-V3/glossary.md
  i18n/es/docusaurus-plugin-content-docs/version-V3/guides/groups.md
  i18n/es/docusaurus-plugin-content-docs/version-V3/guides/identities.md
  i18n/es/docusaurus-plugin-content-docs/version-V3/guides/proofs.md
  i18n/es/docusaurus-plugin-content-docs/version-V3/quick-setup.md
  i18n/es/docusaurus-plugin-content-docs/version-V3/resources.md
  i18n/es/docusaurus-plugin-content-docs/version-V3/subgraph.md
  i18n/es/docusaurus-plugin-content-docs/version-V3/technical-reference/circuits.md
  i18n/es/docusaurus-plugin-content-docs/version-V3/technical-reference/contracts.md
  i18n/es/docusaurus-plugin-content-docs/version-V3/what-is-semaphore.md
Labels: documentation 📖

#67 Spanish translations
  i18n/es/code.json
  i18n/es/docusaurus-plugin-content-docs/version-V3/credits.md
  i18n/es/docusaurus-plugin-content-docs/version-V3/deployed-contracts.md
  i18n/es/docusaurus-plugin-content-docs/version-V3/glossary.md
  i18n/es/docusaurus-plugin-content-docs/version-V3/guides/groups.md
  i18n/es/docusaurus-plugin-content-docs/version-V3/guides/identities.md
  i18n/es/docusaurus-plugin-content-docs/version-V3/guides/proofs.md
  i18n/es/docusaurus-plugin-content-docs/version-V3/quick-setup.md
  i18n/es/docusaurus-plugin-content-docs/version-V3/resources.md
  i18n/es/docusaurus-plugin-content-docs/version-V3/subgraph.md
  i18n/es/docusaurus-plugin-content-docs/version-V3/technical-reference/circuits.md
  i18n/es/docusaurus-plugin-content-docs/version-V3/technical-reference/contracts.md
  i18n/es/docusaurus-plugin-content-docs/version-V3/what-is-semaphore.md
  versioned_docs/version-V3/credits.md
  versioned_docs/version-V3/resources.md
Labels: documentation 📖

#70 New arbitrum contract addresses
  i18n/es/docusaurus-plugin-content-docs/version-V3/deployed-contracts.md
  versioned_docs/version-V3/deployed-contracts.md
Labels: documentation 📖

#73 Algolia configuration
  docusaurus.config.js
Labels: feature :rocket:

#72 New Semaphore proof lib
  i18n/es/docusaurus-plugin-content-docs/version-V3/guides/proofs.md
  src/pages/index.tsx
  versioned_docs/version-V3/guides/proofs.md
Labels: documentation 📖

#74 Warnings for Semaphore groups
  i18n/es/docusaurus-plugin-content-docs/version-V3/guides/groups.md
  i18n/es/docusaurus-plugin-content-docs/version-V3/guides/identities.md
  i18n/es/docusaurus-plugin-content-docs/version-V3/guides/proofs.md
  i18n/es/docusaurus-plugin-content-docs/version-V3/quick-setup.md
  i18n/es/docusaurus-plugin-content-docs/version-V3/technical-reference/contracts.md
  versioned_docs/version-V3/guides/groups.md
  versioned_docs/version-V3/guides/identities.md
Labels: documentation 📖

#75 Change DocSearch styles
  src/css/custom.scss
Labels: design :art:

#76 Add tabs for package managers in spanish doc
  i18n/es/docusaurus-plugin-content-docs/version-V3/quick-setup.mdx
Labels: feature :rocket:
