Repository semaphore-protocol/website, pull requests merged in 2023-05, with the labels that each got.

#92 Add install code block for libraries
  i18n/es/docusaurus-plugin-content-docs/version-V3/guides/groups.mdx
  i18n/es/docusaurus-plugin-content-docs/version-V3/guides/identities.mdx
  i18n/es/docusaurus-plugin-content-docs/version-V3/guides/proofs.mdx
  package.json
  versioned_docs/version-V3/guides/groups.mdx
  versioned_docs/version-V3/guides/identities.mdx
  versioned_docs/version-V3/guides/proofs.mdx
Labels: documentation 📖

#93 Add guide to explain how to fetch on-chain group data
  i18n/es/docusaurus-plugin-content-docs/version-V3/guides/fetching-data.mdx
  versioned_docs/version-V3/guides/fetching-data.mdx
Labels: documentation 📖, feature :rocket:

#95 Add FAQ and Troubleshooting pages
  i18n/es/docusaurus-plugin-content-docs/version-V3/faq.md
  i18n/es/docusaurus-plugin-content-docs/version-V3/troubleshooting.mdx
  versioned_docs/version-V3/faq.md
  versioned_docs/version-V3/troubleshooting.mdx
Labels: documentation 📖, feature :rocket:

#96 Correct conditions to show search bar
  src/theme/Navbar/Search/index.tsx
  src/theme/NavbarItem/index.tsx
Labels: bug 🐛

#97 Add info about the isGroupMember function
  i18n/es/docusaurus-plugin-content-docs/version-V3/guides/fetching-data.mdx
  versioned_docs/version-V3/guides/fetching-data.mdx
Labels: documentation 📖
